version: 0.2
env:
  variables: {}
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-2)
      # Load the url of the image we want to run
      - export RELEASE_IMAGE_URL=$(cat RELEASE_IMAGE_URL.txt)
  build:
    commands:
      - echo "About to exec $RELEASE_IMAGE_URL to $BASE_URL"
      - |
        docker run \
          -e AWS_REGION=us-east-2 \
          -e AWS_CONTAINER_CREDENTIALS_RELATIVE_URI \
          -e BASE_URL \
          -e CLIENT_ID \
          -e ENCRYPTED_CLIENT_SECRET \
          -e TOKEN_ENDPOINT \
          $RELEASE_IMAGE_URL npm run integration-test
